### ISSUE TITLE
how to check the result ?

### ISSUE THREAD

**Issue by yankunsam** [cnf/structhash#7]
type Name struct {
name string

}
data := []byte{"hello"}
The result is not equal to sha1.Sum(data)

So can you give me some advice to this situation?

samyankun@gmail.com

**Comment by cnf** [comment]
```
data := []byte{"hello"}
sha1.Sum(data) 
```
is a checksum of data, structhash is a checksum of a serialized format of a datastructure.

Please have a look at the documentation at https://godoc.org/github.com/cnf/structhash to see what the different functions do.

You can use [Dump](https://godoc.org/github.com/cnf/structhash#Dump) to see what the data being hashed looks like. Mind that a version int is also added.

**Comment by yankunsam** [comment]
Sorry, Can you tell me why the example I list is wrong? I have read your document, but I can not find the answer.

**Comment by cnf** [comment]
I do not understand your "example"

You have a struct you don't use, and a bytestring... then you hash the bytestring...

What are you trying to do?

```
type Name struct {
    name string

}
data := Name{name: "hello"}

// shSha1 and Sha1 are the same.
shSha1 := structhash.Sha1(data, 1)
Sha1 := sha1.Sum(structhash.Dump(c, 1))
```

**Comment by yankunsam** [comment]
I mean how to verify your "structhash.Sha1" is right. I have a struct,
"name " is the only element and I calculate its hash with another string
variable. And the result is wrong. So is it clearly?

Thanks

**Comment by cnf** [comment]
Please read what I replied, I explain what you need to do.

The code you pasted doesn't do anything of relevance.

**Comment by yankunsam** [comment]
package main
import (
        "fmt"
        "crypto/sha1"
        "github.com/cnf/structhash"
        )

type String struct {
        name []byte

}
func main(){
        c := []byte("hello")
        var m  String
        m.name = make([]byte,6)
        copy(m.name,c)
        hash,err := structhash.Hash(m,1)
        if err != nil {
                panic(err)
        }
        fmt.Println(hash)
        fmt.Printf("% x\n",structhash.Sha1(m,1))
        fmt.Printf("% x\n",sha1.Sum(structhash.Dump(m,1)))
        fmt.Printf("% x\n", sha1.Sum(structhash.Dump(m,1)))
        fmt.Printf("% x \n",sha1.Sum(c));

output:

[sam@sam_dev go]$ go run struct.go
v1_f489e1d6a6431529a71f4080231aad34
c6 0c 35 ae 84 22 16 b4 78 6d a4 87 99 e2 2e 4b e6 a2 29 c1
c6 0c 35 ae 84 22 16 b4 78 6d a4 87 99 e2 2e 4b e6 a2 29 c1
c6 0c 35 ae 84 22 16 b4 78 6d a4 87 99 e2 2e 4b e6 a2 29 c1
aa f4 c6 1d dc c5 e8 a2 da be de 0f 3b 48 2c d9 ae a9 43 4d



How about this?

**Comment by cnf** [comment]
```
package main

import (
	"crypto/md5"
	"crypto/sha1"
	"fmt"
	"github.com/cnf/structhash"
)

type String struct {
	name []byte
}

func main() {
	c := []byte("hello")
	var m String
	m.name = make([]byte, 6)
	copy(m.name, c)
	hash, err := structhash.Hash(m, 1)
	if err != nil {
		panic(err)
	}
	fmt.Println(hash)
	fmt.Printf("v1_%x\n", md5.Sum(structhash.Dump(m, 1)))
	fmt.Printf("%x\n", structhash.Sha1(m, 1))
	fmt.Printf("%x\n", sha1.Sum(structhash.Dump(m, 1)))
	fmt.Printf("%x\n", sha1.Sum(c))
}
```
gives

```
$ go run foo.go
v1_f489e1d6a6431529a71f4080231aad34
v1_f489e1d6a6431529a71f4080231aad34
c60c35ae842216b4786da48799e22e4be6a229c1
c60c35ae842216b4786da48799e22e4be6a229c1
aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d
```

This is the expected output

Which part of this confuses you?

**Comment by yankunsam** [comment]
If as you saied, how can I verify the result by your API  is right or wrong?

Thanks!

**Comment by cnf** [comment]
By reading the code, and I just pasted what to do above.

**Comment by cnf** [comment]
structhash is a library for creating hashes of _serialized_ datastructures, so they can be compared. The default hash algorithm used is md5.

https://github.com/cnf/structhash/blob/master/structhash_examples_test.go contains examples.

You can read the code here to see how it works: https://github.com/cnf/structhash/blob/master/structhash.go

```
package main

import (
	"crypto/md5"
	"fmt"

	"github.com/cnf/structhash"
)

func main() {
	type Person struct {
		Name   string
		Age    int
		Emails []string
		Extra  map[string]string
		Spouse *Person
	}
	bill := &Person{
		Name:   "Bill",
		Age:    24,
		Emails: []string{"bob@foo.org", "bob@bar.org"},
		Extra: map[string]string{
			"facebook": "Bob42",
		},
	}
	bob := &Person{
		Name:   "Bob",
		Age:    42,
		Emails: []string{"bob@foo.org", "bob@bar.org"},
		Extra: map[string]string{
			"facebook": "Bob42",
		},
		Spouse: bill,
	}
	version := 1

	hash, err := structhash.Hash(bob, version)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s\n", hash)
	fmt.Printf("%s\n", structhash.Dump(bob, version))
	fmt.Printf("v%d_%x\n", version, md5.Sum(structhash.Dump(bob, version)))
}
```
output:

```
$ go run bar.go
v1_6a50d73f3bd0b9ebd001a0b610f387f0
{Age:42,Emails:["bob@foo.org","bob@bar.org"],Extra:["facebook":"Bob42"],Name:"Bob",Spouse:{Age:24,Emails:["bob@foo.org","bob@bar.org"],Extra:["facebook":"Bob42"],Name:"Bill",Spouse:<invalid Value>}}
v1_6a50d73f3bd0b9ebd001a0b610f387f0
```

I hope this clears things up.
